			  <option value="EU"  >EU868 Europe 868Mhz (863~870) </option>
			  <option value="CN"  >CN470 China 470MHz (470~510) </option>
			  <option value="US"  >US915 United States 915Mhz (902~928) </option>
			  <option value="AU"  >AU915 Australia 915Mhz (915~928) </option>
			  <option value="IN"  >IN865 India 865MHz (865~867) </option>
			  <option value="KR"  >KR920 Korea 920MHz (920~923) </option>
			  <option value="AS1" >AS923 Asia 923MHz (920~923) </option>
			  <option value="AS2" >AS923 Asia 923MHz (923~925) </option>
			  <option value="RU"  >RU864 Russia 864MHz (864~870) </option>

