
  <title>Dragino LoRa Gateway</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />

  <link rel="stylesheet" type="text/css" href="/static/resources/LoRaGateway.css">  
  <link rel="stylesheet" href="/static/resources/config.css">
  <!--  <link rel="stylesheet" href="/static/resources/bootstrap.min.css"> -->
	<link rel="stylesheet" href="/static/resources/font-awesome.min.css">
  
 <!--  
	<script src="/static/resources/jquery.min.js"></script>
 	<script src="/static/resources/bootstrap.min.js"></script>
	<script src="/static/resources/popper.min.js"></script>
 -->

	<link rel="shortcut icon" href="/static/resources/favicon.ico">

	<script>
  	function toggleNavbar() {
	 	 var x = document.getElementById("docTopnav");
	 	 if (x.className === "topnav") {
	    x.className += " responsive";
	  	} 
	 	 	else {
	    	x.className = "topnav";
		  }
		}
	</script>

