<option value="eu1.loriot.io">Frankfurt - eu1.loriot.io</option>
<option value="eu2.loriot.io">Amsterdam - eu2.loriot.io</option>
<option value="eu3.loriot.io">Madrid - eu3.loriot.io</option>
<option value="uk1.loriot.io">London - uk1.loriot.io</option>
<option value="af1.loriot.io">Capetown - af1.loriot.io</option>
<option value="ap1.loriot.io">Singapore - ap1.loriot.io</option>
<option value="au1.loriot.io">Sydney - au1.loriot.io</option>
<option value="cn1.loriot.io">Shenzen - cn1.loriot.io</option>
<option value="ap2.loriot.io">Tokyo - ap2.loriot.io</option>
<option value="ap3.loriot.io">Mumbai - ap3.loriot.io</option>
<option value="us1.loriot.io">California - us1.loriot.io</option>
<option value="us2.loriot.io">New York - us2.loriot.io</option>
<option value="sa1.loriot.io">Sao Paulo - sa1.loriot.io</option>



