<div class="topnav" id="docTopnav">

  <div style="background-color: white; padding-right: 15px">
    <a href="http://www.dragino.com">
    <img class="toplogo" src="/static/img/DRAGINO_logo_transparent.png">
    </a>
  </div>

  <div class="dropdown"> <!-- LoRa Parameter -->
    <button class="dropbtn">LoRa <span class="fas fa-caret-down"></span></button>
    <div class="dropdown-content">
      <a href="/cgi-bin/lora-lora.has">LoRa</a>
      <a href="/cgi-bin/lora-abp.has">ABP Decryption</a>
    </div>
  </div> 
  
  <div><a href="/cgi-bin/lorawan.has">LoRaWAN</a></div>

  <div class="dropdown"> <!-- MQTT -->
	<button class="dropbtn">MQTT <span class="fas fa-caret-down"></span></button>
    <div class="dropdown-content">
      <a href="/cgi-bin/mqtt.has">MQTT Client</a>
      <a href="/cgi-bin/mqtt-chan.has">Channels</a>
      <a href="/cgi-bin/mqtt-cert.has">Certificates</a>
    </div>
  </div> 

  <div class="dropdown"> <!-- TCP -->
    <button class="dropbtn">TCP <span class="fas fa-caret-down"></span></button>
    <div class="dropdown-content">
      <a href="/cgi-bin/tcp-client.has">TCP Client</a>
      <a href="/cgi-bin/tcp-chan.has">Channels</a>
    </div>
  </div> 

  <div><a href="/cgi-bin/http-client.has">HTTP</a></div>

  <div class="dropdown"> <!-- Custom -->
    <button class="dropbtn">Custom <span class="fas fa-caret-down"></span></button>
    <div class="dropdown-content">
      <a href="/cgi-bin/custom.has">Custom Script</a>
      <a href="/cgi-bin/custom-script.has">Script Management</a>
    </div>
  </div> 
  
 <div class="dropdown"> <!-- System -->
    <button class="dropbtn">System <span class="fas fa-caret-down"></span></button>
    <div class="dropdown-content">
		<a href="/cgi-bin/system-overview.has">System Overview</a>
		<a href="/cgi-bin/system-network.has">Network</a>
		<a href="/cgi-bin/system-wifi.has">WiFi</a>
		<a href="/cgi-bin/system-cellular.has">Cellular</a>
		<a href="/cgi-bin/system-status.has">Network Status</a>
		<a href="/cgi-bin/system-rssh.has">Remote Mgmt</a>
		<a href="/cgi-bin/system-firmware.has">Firmware Upgrade</a>
		<a href="/cgi-bin/system-reboot.has">Reboot / Reset</a>
		<a href="/cgi-bin/system-package.has">Package Maintain</a>
    </div>
  </div> 
 
 <div class="dropdown"> <!-- LogRead -->
    <button class="dropbtn">LogRead<span class="fas fa-caret-down"></span></button>
    <div class="dropdown-content">
      <a href="/cgi-bin/log-lora.has">LoRa Log</a>
      <a href="/cgi-bin/log-sys.has">System Log</a>
    </div>
  </div> 

  <div><a href="/cgi-bin/luci">LuCI</a></div>

  <div><a href="/cgi-bin/dragino.has">Home</a></div>

  <div id="refreshIndicate">AUTO REFRESH</div>

  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="toggleNavbar()">&#9776;</a>
  
</div>

