			  <option value="1" >1: AU915 (915.2~916.6) </option>
			  <option value="2" >2: AU915 (916.8~918.2) </option> 
			  <option value="3" >3: AU915 (918.4~919.8) </option>
			  <option value="4" >4: AU915 (920.0~921.4) </option>
			  <option value="5" >5: AU915 (921.6~923.0) </option>
			  <option value="6" >6: AU915 (923.2~924.6) </option>
			  <option value="7" >7: AU915 (924.8~926.2) </option>
			  <option value="8" >8: AU915 (926.4~927.8) </option>	 

