#!/bin/sh /etc/rc.common
START=99

start()
{	
sta_disabled=$(uci -q get wireless.sta_0.disabled)
ap_disabled=$(uci -q get wireless.ap_0.disabled)

# If sta iface is not enabled, exit
if [ $sta_disabled != "0" ]; then
  exit
fi

# Check if sta and ap interfaces are both enabled and working 
ssid_count=$(iw dev | grep -c ssid)
if [ $sta_disabled == "0" ] && [ $ap_disabled == "0" ] && [ $ssid_count == "2" ]; then
  # All ok, exit
  exit
else
  sleep 10 # Wait to see if it will connect
fi

# Check if sta and ap interfaces are both enabled and working 
ssid_count=$(iw dev | grep -c ssid)
if [ $sta_disabled == "0" ] && [ $ap_disabled == "0" ] && [ $ssid_count == "2" ]; then
  # All ok, exit
  exit
else
  sleep 20 # Wait to see if it will connect
fi

# Check again
ssid_count=$(iw dev | grep -c ssid)
if [ $sta_disabled == "0" ] && [ $ap_disabled == "0" ] && [ $ssid_count == "2" ]; then
  # All ok, exit
  exit
else
  # Still not connected; disable sta interface and restart networking
  uci set wireless.sta_0.disabled=1
  uci commit wireless
  logger "[WiFi.WAN]: WiFi WAN did not connect; disabled"
  /etc/init.d/network restart
  sleep 10
  /etc/init.d/fallbackip start
fi
}


