#!/bin/sh /etc/rc.common
START=99

start()
{	
    logger "Adding FallBack IP"
    logger "Checking bridge mode or not"
    IS_BRIDGE=`uci get network.lan.type`
	IS_LPS8=`hexdump -v -e '11/1 "%_p"' -s $((0x908)) -n 11 /dev/mtd6 |grep lps8 -c`
	
	if [ "$IS_LPS8" = "1" ];then
		logger "Set up WAN port for fall back ip"
		ifconfig eth1:9 172.31.255.254 netmask 255.255.255.252
    else 
		if [ "$IS_BRIDGE" = "bridge" ];then
			logger "Device is in bridging mode."
			ifconfig br-lan:9 172.31.255.254 netmask 255.255.255.252
		else 
			logger "Device is not in bridging mode."
			ifconfig eth0:9 172.31.255.254 netmask 255.255.255.252
    	fi
	fi
}
