#!/bin/sh /etc/rc.common
START=99

start()
{	
    echo "Adding FallBack IP"
    echo "Checking bridge mode or not"
    IS_BRIDGE=`uci get network.lan.type`
	IS_LPS8=`hexdump -v -e '11/1 "%_p"' -s $((0x908)) -n 11 /dev/mtd6 |grep lps8 -c`
	
	if [ "$IS_LPS8" = "1" ];then
		has_ETH0=`uci get network.lan.ifname`
		if [ "$has_ETH0" = "eth0" ];then
			uci delete network.lan
			uci commit network
			/etc/init.d/network restart
		fi
		echo "Set up WAN port for fall back ip"
		ifconfig eth1:9 172.31.255.254 netmask 255.255.255.252
    else 
		if [ "$IS_BRIDGE" = "bridge" ];then
			echo "Device is in bridging mode."
			ifconfig br-lan:9 172.31.255.254 netmask 255.255.255.252
		else 
			echo "Device is not in bridging mode."
			ifconfig eth0:9 172.31.255.254 netmask 255.255.255.252
    	fi
	fi
}
